package com.connecthub.message.service;

import com.connecthub.message.dto.SendMessageRequest;
import com.connecthub.message.dto.StompPayload;
import com.connecthub.message.entity.Message;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
@Slf4j
public class RabbitMQListener {

    private final MessageService messageService;

    @RabbitListener(queues = "${connecthub.rabbitmq.queue}")
    public void handleMessage(StompPayload payload) {
        log.info("Received message from RabbitMQ: type={}, id={}", payload.getType(), payload.getMessageId());
        
        try {
            switch (payload.getType()) {
                case CHAT_MESSAGE:
                case IMAGE:
                case FILE:
                    saveMessage(payload);
                    break;
                case MESSAGE_DELETE:
                    messageService.deleteMessage(payload.getMessageId(), payload.getSenderId());
                    break;
                case MESSAGE_PIN:
                    messageService.pinMessage(payload.getMessageId(), payload.isPinned());
                    break;
                case MESSAGE_EDIT:
                    messageService.editMessage(payload.getMessageId(), payload.getSenderId(), payload.getContent());
                    break;
                default:
                    log.warn("Unhandled message type: {}", payload.getType());
            }
        } catch (Exception e) {
            log.error("Error processing RabbitMQ message: {}", e.getMessage());
        }
    }

    private void saveMessage(StompPayload payload) {
        SendMessageRequest request = SendMessageRequest.builder()
                .roomId(payload.getRoomId())
                .senderId(payload.getSenderId())
                .senderUsername(payload.getSenderUsername())
                .senderFullName(payload.getSenderFullName())
                .senderAvatarUrl(payload.getSenderAvatarUrl())
                .content(payload.getContent())
                .type(Message.MessageType.valueOf(payload.getType().name()))
                .mediaUrl(payload.getMediaUrl())
                .replyToMessageId(payload.getReplyToId())
                .build();
        
        // We need to pass the messageId as well if we want to use the one generated by websocket-handler
        // Let's modify MessageService to allow passing an ID
        messageService.saveMessageWithId(payload.getMessageId(), request);
    }
}
